version: "2"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    environment:
      REVERSE_PROXY_DOMAIN_NAME: ${REVERSE_PROXY_DOMAIN_NAME}

  mattermost:
    image: mattermost/mattermost-prod-app
    environment:
      MATTERMOST_ENABLE_SSL: "true"
      DB_HOST: db
      MM_DBNAME: mattermost
      MM_USERNAME: mattermost
      MM_PASSWORD: mattermost
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-config:/mattermost/config

  db:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  mattermost-data:
    driver: local
  mattermost-config:
    driver: local
  db-data:
    driver: local

